// packages/chunter/src/components/PageProperties.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">

import { defineComponent, PropType, ref } from 'vue'
import { Class, Ref, VDoc } from '@anticrm/platform'

import { getPresentationUI } from '@anticrm/presentation-ui/src/utils'
import { getPresentationCore } from '../utils'

import OwnAttributes from '@anticrm/presentation-ui/src/components/OwnAttributes.vue'
import StringPresenter from '@anticrm/presentation-ui/src/components/presenter/StringPresenter.vue'
import Button from '@anticrm/sparkling-controls/src/Button.vue'

export default defineComponent({
  components: { StringPresenter, OwnAttributes, Button },
  props: {
    _class: {
      type: String as unknown as PropType<Ref<Class<VDoc>>>,
      required: true
    },
    object: Object
  },
  setup (props, context) {
    const presentationCore = getPresentationCore()
    const ui = getPresentationUI()

    const TITLE = 'title'
    const title = ref(presentationCore.getEmptyAttribute(props._class))

    const model = ui.getClassModel(props, model => {
      title.value = model.getAttribute(TITLE)
      return model.filterAttributes([TITLE])
    })

    return {
      model,
      title
    }
  }
})
</script>

<template>
  <div class="chunter-page-properties">
    <div>
      <StringPresenter class="caption-1" :attribute="title" v-model="object[title.key]" />
    </div>

    <div class="attributes">
      <OwnAttributes
        class="group"
        v-for="group in model.getGroups()"
        :_class="group._class"
        :model="model"
        :object="object"
        :key="group._class"
      ></OwnAttributes>
    </div>
  </div>
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

.chunter-page-properties {
  .attributes {
    display: flex;
    flex-wrap: wrap;

    margin-top: 1em;

    .group {
      padding: 0.5em;
    }
  }
}
</style>

// plugins/chunter/src/components/internal/PageProperties.svelte
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script type="ts">
  import { Ref, Class, Obj } from '@anticrm/core'
  import chunter, { Page } from '../..'
  import core from '@anticrm/platform-core'
  import { getPresentationService } from '../../utils'
  import { AttrModel, ClassModel } from '@anticrm/presentation'

  import Properties from '@anticrm/presentation/src/components/internal/Properties.svelte'
  import AttributeEditor from '@anticrm/presentation/src/components/AttributeEditor.svelte'

  export let _class: Ref<Class<Obj>>
  export let object: Page

  let model: ClassModel | undefined
  let title: AttrModel | undefined

  $: getPresentationService()
    .then(service => service.getClassModel(_class, core.class.VDoc))
    .then(m => { 
      title = m.getAttribute('title')
      model = m.filterAttributes(['title']) 
    })
</script>

{ #if model && title }
<div>
  <div class="caption-1"><AttributeEditor attribute={title} bind:value={object.title} /></div>
</div>
<Properties {model} bind:object={object}/>
{ /if }
