// plugins/platform-ui/src/components/internal/Root.svelte
<script lang="ts">
  import type { Platform, Status } from "@anticrm/platform";
  import { PlatformStatus, Severity } from "@anticrm/platform";
  import type { UIService, AnyComponent } from "../..";
  import { setContext } from "svelte";

  import Theme from "@anticrm/sparkling-theme/src/components/Theme.svelte";
  import StatusComponent from "./Status.svelte";
  import Clock from "./Clock.svelte";
  import Component from "../Component.svelte";

  import { 
    CONTEXT_PLATFORM,
    CONTEXT_PLATFORM_UI,
  } from '../..'

  export let platform: Platform;
  export let ui: UIService;

  setContext(CONTEXT_PLATFORM, platform)
  setContext(CONTEXT_PLATFORM_UI, ui)

  let currentApp: AnyComponent;
  const location = ui.getLocation()
  location.subscribe((loc) => {
    currentApp = loc.pathname.split("/")[1] as AnyComponent;
  });

  let status: Status = { severity: Severity.OK, code: 0, message: "" };

  platform.addEventListener(
    PlatformStatus,
    async (event: string, platformStatus: Status) => {
      status = platformStatus;
    }
  )
</script>

<style lang="scss">
  $status-bar-height: 20px;
  $pictogram-size: 48px;

  #ui-root {
    display: flex;
    flex-direction: column;

    height: 100vh;

    .status-bar {
      background-color: var(--theme-bg-color);
      color: var(--theme-content-color);
      height: $status-bar-height;
      line-height: $status-bar-height;
      border-bottom: 1px solid var(--theme-nav-color);

      .container {
        display: flex;

        .logo {
          width: $pictogram-size;
          text-align: center;
          /*padding-left: 1em;*/
          /*padding-right: 1em;*/

          font-size: 1.25em;
          font-weight: 700;

          border-right: 1px solid var(--theme-nav-color);
        }

        .status-messages {
          flex-grow: 1;
          text-align: center;
        }

        .widgets {
          display: flex;
          flex-direction: row-reverse;

          // .widget {
          //   border-left: 1px solid var(--theme-nav-color);
          //   padding-right: 1em;
          //   padding-left: 1em;
          //   font-weight: 700;
          // }

          .clock {
            border-left: 1px solid var(--theme-nav-color);
            padding-right: 1em;
            padding-left: 1em;
            font-weight: 700;
          }
        }
      }
    }

    .error {
      margin-top: 45vh;
      text-align: center;
    }

    .app {
      height: calc(100vh - #{$status-bar-height});
      background-color: var(--theme-bg-color);
    }
  }
</style>

<Theme>
  <div id="ui-root">
    <div class="status-bar">
      <div class="container">
        <div class="logo">&#x24C5;</div>
        <div class="status-messages">
          <StatusComponent {status} />
        </div>
        <div class="widgets">
          <div class="clock">
            <Clock />
          </div>
          <!-- <div v-for="widget in widgets" :key="widget" class="widget">
            <widget :component="widget" />
          </div> -->
        </div>
      </div>
    </div>
    <div class="app">
      {#if currentApp}
        <Component is={currentApp} />
      {:else}
        <div class="caption-1 error">No application provided. {currentApp}</div>
      {/if}
    </div>
  </div>
</Theme>

// plugins/platform-vue/src/internal/Root.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
import { Platform, TaskEvent, Task } from '@anticrm/platform'
import { defineComponent, computed, reactive, onMounted, onUnmounted, inject, ref, toRefs } from 'vue'
import ui, { AnyComponent } from '@anticrm/platform-ui'
import vue, { getVueService, getPlatform } from '..'

import Clock from './widgets/Clock.vue'
import Network from './widgets/Network.vue'

//const defaultStatus = 'Система готова к работе.'
const defaultStatus = ''

export default defineComponent({
  components: { Network, Clock },
  setup () {
    const platform = getPlatform()
    const status = ref(defaultStatus)
    const error = ref('')
    platform.addEventListener(TaskEvent.Start, (task: Task) => {
      status.value = task.name + '...'
    })
    platform.addEventListener(TaskEvent.Done, (task: Task) => {
      status.value = defaultStatus
    })
    platform.addEventListener(TaskEvent.Error, (err: Error) => {
      error.value = err.message
    })

    const vueService = getVueService()
    const current = computed(() => vueService.getLocation())
    return { status, error, current, appLoader: vue.component.AppLoader }
  },
})
</script>

<template>
  <div id="rich-client">
    <div class="status-bar">
      <div class="container">
        <div class="logo">
          <span class="text-1">anticrm</span>
          <span class="text-2">Platform</span>&nbsp;
          <span class="text-3">0.1.0</span>
        </div>
        <div class="status-messages">{{status}} {{error}}</div>
        <div class="widgets">
          <div class="clock">
            <Clock />
          </div>
          <div>
            <Network />
          </div>
        </div>
      </div>
    </div>
    <div class="app">
      <widget
        v-if="current.app"
        :component="current.app"
        :path="current.path"
        :params="current.params"
        :fallback="appLoader"
      />
      <div v-else class="caption-1">Huston, no default application provided.</div>
    </div>
  </div>
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_globals.scss";
@import "~@anticrm/sparkling-theme/css/_variables.scss";

$status-bar-height: 20px;

#rich-client {
  @include root-style;

  display: flex;
  flex-direction: column;

  height: 100vh;

  .status-bar {
    background-color: $content-color;
    color: $content-bg-color;
    height: $status-bar-height;
    line-height: $status-bar-height;
    // border-bottom: 1px solid red;
    // box-sizing: border-box;

    .container {
      display: flex;
      .logo {
        flex-grow: 1;
        padding-left: 1em;
        padding-right: 1em;
        .text-1 {
          font-size: 1em;
          font-weight: 400;
        }
        .text-2 {
          font-size: 1.25em;
          font-weight: 700;
        }
        .text-3 {
          font-size: 1em;
          font-weight: 700;
        }
      }

      .status-messages {
        flex-grow: 2;
      }

      .widgets {
        flex-grow: 4;
        display: flex;
        flex-direction: row-reverse;

        .clock {
          padding-right: 1em;
          padding-left: 0.5em;
          font-size: 1em;
          font-weight: 700;
        }
      }
    }
  }

  .app {
    height: calc(100vh - #{$status-bar-height});
    background-color: $content-bg-color;
  }
}
</style>
