// packages-v2/sparkling-controls/src/ScrollView.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<template>
  <div class="sparkling-scroll-view">
    <div class="container">
      <slot />
    </div>
  </div>
</template>

<style lang="scss">
.sparkling-scroll-view {
  position: relative;

  .container {
    overflow: scroll;
    position: absolute;
    height: 100%;
    width: 100%;
  }
}
</style>

// packages/sparkling-controls/src/ScrollView.svelte
<script lang="ts">
	// Copyright © 2020 Anticrm Platform Contributors.
	//
	// Licensed under the Eclipse Public License, Version 2.0 (the "License");
	// you may not use this file except in compliance with the License. You may
	// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
	//
	// Unless required by applicable law or agreed to in writing, software
	// distributed under the License is distributed on an "AS IS" BASIS,
	// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	//
	// See the License for the specific language governing permissions and
	// limitations under the License.
	export let stylez: string = ''
	export let scrollPosition: number = 0
</script>

<div class="scroll-view" style={stylez}>
	<div class="container">
		<slot />
	</div>
</div>

<style lang="scss">
	.scroll-view {
		position: relative;

		.container {
			overflow: scroll;
			position: absolute;
			height: 100%;
			width: 100%;
		}
	}
</style>
