// v0.4/sparkling/controls/src/Button.svelte
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
  import Spinner from './Spinner.svelte'

  export let label: string = ''
  export let primary: boolean = false
  export let disabled: boolean = false
  export let loading: boolean = false
  export let width: string

</script>

<button class="button" class:primary={primary} disabled={disabled || loading}
        style="{width ? 'width: ' + width : ''}" on:click>
  {#if loading}
    <Spinner/>
  {:else}
    {label}
  {/if}
</button>

<style lang="scss">
  .button {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 48px;
    padding: 0 25px;
    color: var(--theme-caption-color);
    background-color: var(--theme-button-bg-enabled);
    border: 1px solid var(--theme-button-border-enabled);
    border-radius: 12px;
    outline: none;
    cursor: pointer;
    font-family: inherit;
    font-size: 14px;
    font-weight: 600;
    backdrop-filter: blur(12px);
    &:hover {
      background-color: var(--theme-button-bg-hovered);
      border-color: var(--theme-button-border-hovered);
    }
    &:focus {
      background-color: var(--theme-button-bg-focused);
      border-color: var(--theme-button-border-focused);
    }
    &:active {
      background-color: var(--theme-button-bg-pressed);
      border-color: var(--theme-button-border-pressed);
    }
    &:disabled {
      background-color: var(--theme-button-bg-disabled);
      border-color: var(--theme-button-border-disabled);
      color: rgb(var(--theme-caption-color) / 40%);
      cursor: not-allowed;
    }
  }

  .primary {
    background-color: var(--theme-primary-enabled);
    border-color: var(--theme-primary-border);
    &:hover {
      background-color: var(--theme-primary-hovered);
      border-color: var(--theme-primary-border);
    }
    &:focus {
      background-color: var(--theme-primary-focused);
      border-color: var(--theme-primary-focused-border);
      box-shadow: 0 0 0 2px var(--theme-primary-outline);
    }
    &:active {
      background-color: var(--theme-primary-pressed);
      border-color: var(--theme-primary-border);
      box-shadow: none;
    }
    &:disabled {
      background-color: var(--theme-primary-disabled);
      border-color: var(--theme-primary-border);
      color: rgb(var(--theme-caption-color) / 60%);
      cursor: not-allowed;
    }
  }

</style>

// packages-v2/sparkling-controls/src/Button.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    disabled: Boolean
  }
})
</script>

<template>
  <button type="button" class="sparkling-button" :disabled="disabled">
    <slot />
  </button>
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

.sparkling-button {
  display: inline-block;
  border: 1px solid currentColor;
  border-radius: 2em;
  padding: 0.5em 1.33em 0.5em;
  box-sizing: border-box;
  cursor: pointer;
  user-select: none;
  text-align: center;

  font: inherit;
  font-weight: 400;

  color: inherit;
  background-color: inherit;

  &:focus {
    outline: none;
    border-color: $highlight-color;
    box-shadow: inset 0px 0px 2px 0px $highlight-color;
  }

  &.large {
    padding: 0.75em 1.5em 0.75em;
  }
  &.small {
    padding: 0 0.6em 0;
  }

  &:hover {
    border-color: $highlight-color;
    // color: $highlight-color;
    // background-color: $highlight-color;
    background-color: darken($highlight-color, 10%);
  }

  &.primary {
    // border-color: $highlight-color;
    background-color: $highlight-color;
    // color: $nav-bg-color;
    font-weight: bold;
  }

  &:hover.primary {
    background-color: darken($highlight-color, 5%);
    // border-color: $highlight-color;
    // box-shadow:inset 0px 0px 3px 0px currentColor;
    // color: $highlight-color;
  }
}
</style>
