// packages/sparkling-controls/src/EditBox.svelte
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
  export let width: string = '300px'
  export let value: string
  export let placeholder: string
  export let id: string

  let input: HTMLElement
</script>

<div class="editbox" style='width: {width}' on:click={input.focus()}>
  <input
    bind:this={input}
    id={id}
    type="text"
    bind:value={value}
    {placeholder}
    on:input
    on:focus
    on:change
  />
</div>

<style lang="scss">
  .inline-edit {
    min-width: 12em;
    display: inline-block;
  }

  input {
    border: none;
    width: calc(100% - 2px);
    color: var(--theme-content-color);
    background-color: transparent;
    font: inherit;

    &:focus {
      outline: none;
    }
  }
</style>

// packages-v2/sparkling-controls/src/EditBox.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->


<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    modelValue: String
  }
})
</script>

<template>
  <input
    class="sparkling-edit-box"
    :value="modelValue"
    @input="$emit('update:modelValue', $event.target.value)"
  />
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

.sparkling-edit-box {
  border: 1px solid $workspace-separator-color;
  border-radius: 0.5em;
  padding: 0.5em 0.75em;
  background-color: $nav-bg-color;
  box-sizing: border-box;

  &:focus {
    outline: none;
    border-color: $highlight-color;
  }
}
</style>
