// plugins/platform-ui/src/components/EditBox.svelte
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
  import Icon from './Icon.svelte'
  import { Asset } from "@anticrm/platform-ui";

  export let icon: Asset | undefined  
  export let width: string = '300px'
  export let id: string
  export let value: string
  export let placeholder: string
  export let iconRight: boolean = false

  let input: HTMLElement
</script>

<div class="editbox wIcon" style='width: {width}' on:click={input.focus()}>
  {#if (!iconRight)}
    <Icon {icon} />
    <div class="separator"></div>
  {/if}
  <input
    bind:this={input}
    id={id}
    type="text"
    bind:value={value}
    {placeholder}
    on:input
    on:focus
    on:change
  />
  {#if (iconRight)}
    <div class="separator"></div>
    <Icon {icon} />
  {/if}
</div>

<style lang="scss">
  .wIcon {
    display: flex;
    flex-direction: row;
    align-items: center;
  }
  .separator {
    width: 7px;
  }

  input {
    border: none;
    width: 100%;
    color: var(--theme-content-color);
    background-color: transparent;
    font: inherit;

    &:focus {
      outline: none;
    }
  }
</style>

// plugins/sparkling-controls/src/EditBox.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->


<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  props: {
    modelValue: String
  }
})
</script>

<template>
  <input
    class="sparkling-editbox"
    :value="modelValue"
    @input="$emit('update:modelValue', $event.target.value)"
  />
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

.sparkling-editbox {
  border: 1px solid $workspace-separator-color;
  border-radius: 0.5em;
  padding: 0.5em 0.75em;
  background-color: $nav-bg-color;
  box-sizing: border-box;

  &:focus {
    outline: none;
    border-color: $highlight-color;
  }
}
</style>
