// plugins/sparkling-rich/src/EditorContent.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
import { defineComponent, onMounted, ref, watch, computed } from 'vue'

import { DOMParser, DOMSerializer, Node } from "prosemirror-model"

import { schema } from "./internal/schema"

import { EditorState } from "prosemirror-state"
import { EditorView } from "prosemirror-view"

import { undo, redo, history, closeHistory } from "prosemirror-history"
import { keymap } from "prosemirror-keymap"

import { Selection, TextSelection, NodeSelection, AllSelection } from "prosemirror-state"

import {  wrapIn, setBlockType, chainCommands, toggleMark, exitCode,
  joinUp, joinDown, lift, selectParentNode, baseKeymap} from "prosemirror-commands"
import { wrapInList, splitListItem, liftListItem, sinkListItem } from "prosemirror-schema-list"
import {  undoInputRule, inputRules, wrappingInputRule, textblockTypeInputRule,
  smartQuotes, emDash, ellipsis} from "prosemirror-inputrules"

import { buildKeymap } from './internal/keymap'
import { buildInputRules } from './internal/input_rules'
import { Commands } from './internal/commands'

const mac = typeof navigator != "undefined" ? /Mac/.test(navigator.platform) : false


export default defineComponent({
  components: {},
  props: {
    content: String,  // HTML content.
    hoverMessage: {
      type: String,
      default: "Placeholder...",
    },
  },
  model: {
    'props': "content",
  },
  setup(props, context) {
    const root = ref(null)

    let editRoot = document.createElement('div')

    const parser = new window.DOMParser()
    const element = parser.parseFromString(props.content, 'text/html').body

    let isEmpty = computed(() => {
      return props.content.length === 0 || props.content === "<p><br></p>"
    })

    let state = EditorState.create({
      schema,
      doc: DOMParser.fromSchema(schema).parse(element),
      plugins: [
        history(),
        buildInputRules(),
        keymap(buildKeymap()),
        keymap({
          'Enter': (state, dispatch) => {

            context.emit('submit', view.dom.innerHTML)
            return true;
          }
        }),
      ]
    })
    let view = new EditorView(editRoot, {
      state,
      dispatchTransaction(transaction) {
        let newState = view.state.apply(transaction)
        view.updateState(newState)

        context.emit("update:content", view.dom.innerHTML)

        // Check types
        let marks = view.state.storedMarks || view.state.selection.$from.marks()

        let isBold = schema.marks.strong.isInSet(marks) != null
        let isItalic = schema.marks.em.isInSet(marks) != null
        let isStrike = schema.marks.strike.isInSet(marks) != null
        let isUnderline = schema.marks.underline.isInSet(marks) != null

        let evt = {
          isEmpty: isEmpty.value,
          bold: isBold, isBoldEnabled: Commands.toggleStrong(view.state, null),
          italic: isItalic, isItalicEnabled: Commands.toggleItalic(view.state, null),
          strike: isStrike, isStrikeEnabled: Commands.toggleStrike(view.state, null),
          underline: isUnderline, isUnderlineEnabled: Commands.toggleUnderline(view.state, null)
        }
        context.emit("styleEvent", evt)
      }
    })

    onMounted(() => {
      root.value.appendChild(editRoot)
    })
    watch(() => props.content, content => {
      if (content != view.dom.innerHTML) {

        const parser = new window.DOMParser()
        const element = parser.parseFromString(props.content, 'text/html').body
        // console.log("parser body:", element)
        let newDoc = DOMParser.fromSchema(schema).parse(element)

        let op = state.tr.setSelection(new AllSelection(state.doc)).replaceSelectionWith(newDoc);
        let newState = state.apply(op)

        view.updateState(newState)

        view.focus()
      }
    })

    return {
      root,
      view,
      isEmpty,

      // Some operations
      toggleBold() {
        Commands.toggleStrong(view.state, view.dispatch)
        view.focus()
      },
      toggleItalic() {
        Commands.toggleItalic(view.state, view.dispatch)
        view.focus()
      },
      toggleStrike() {
        Commands.toggleStrike(view.state, view.dispatch)
        view.focus()
      },
      toggleUnderline() {
        Commands.toggleUnderline(view.state, view.dispatch)
        view.focus()
      },
      toggleUnOrderedList() {
        Commands.toggleUnOrdered(view.state, view.dispatch)
        view.focus()
      },
      toggleOrderedList() {
        Commands.toggleOrdered(view.state, view.dispatch)
        view.focus()
      }
    }
  },
})
</script>

<template>
  <div class="sparkling-rich-editor-content">
    <div v-if="isEmpty" class="hover-message">{{hoverMessage}}</div>
    <div class="edit-box" ref="root"></div>
  </div>
</template>


<style lang="scss">
.sparkling-rich-editor-content {
  .chunter-curson-span {
    width: 1px;
  }
  .hover-message {
    margin: 5px;
    color: #aaaaaa;
  }
  .edit-box {
    width: 100%;
    div {
      outline: none;
      p {
        margin: 5px;
      }
      blockquote {
        border-left: 1.5px solid #bbb;
        margin: 5px;
      }
    }
  }
  .edit-box:focus {
    outline: none;
  }
  .hover-message {
    position: absolute;
    pointer-events: none;
  }
}
</style>

// packages/sparkling-rich/src/EditorContent.svelte
<script lang="ts">
	import { DOMParser, Fragment, Slice, Mark, MarkType } from 'prosemirror-model'

	import { schema } from './internal/schema'

	import { AllSelection, EditorState, Transaction } from 'prosemirror-state'
	import { EditorView } from 'prosemirror-view'

	import { history } from 'prosemirror-history'
	import { keymap } from 'prosemirror-keymap'

	import { buildKeymap } from './internal/keymap'
	import { buildInputRules } from './internal/input_rules'
	import { Commands } from './internal/commands'
	import { EditorContentEvent } from './index'

	import { createEventDispatcher, onMount } from 'svelte'

	const dispatch = createEventDispatcher()

	const mac =
		typeof navigator != 'undefined' ? /Mac/.test(navigator.platform) : false

	export let content: string = ''
	export let hoverMessage: string = 'Placeholder...'
	export let triggers: string[] = []
	export let transformInjections: (
		state: EditorState
	) => Promise<Transaction | null>

	// Perform update of values are changed
	$: updateValue()

	// Internal variables
	let view: EditorView
	let state: EditorState
	let root: HTMLElement
	let rootElement: HTMLElement

	let isEmpty: boolean = checkEmpty(content)

	function checkEmpty(value: string): boolean {
		return value.length === 0 || value === '<p><br></p>' || value === '<p></p>'
	}

	function findCompletion(
		sel: any
	): { completionWord: string; completionEnd: string } {
		var completionWord = ''
		var completionEnd = ''
		if (sel.$from.nodeBefore != null) {
			let val = sel.$from.nodeBefore.textContent
			let p = -1
			for (p = val.length - 1; p >= 0; p--) {
				if (val[p] === ' ' || val[p] === '\n') {
					//Stop on WS
					break
				}
				for (let ti = 0; ti < triggers.length; ti++) {
					let t = triggers[ti]
					if (val.substring(p, t.length) == t) {
						// we found trigger, -1 to pos
						p -= t.length
						break
					}
				}
			}
			if (p != -1) {
				val = val.substring(p + 1)
			}
			completionWord = val
		}
		if (sel.$from.nodeAfter != null) {
			completionEnd = sel.$from.nodeAfter.textContent
		}
		return { completionWord, completionEnd }
	}

	function emitStyleEvent() {
		let sel = view.state.selection
		var { completionWord, completionEnd } = findCompletion(sel)

		let cursor = view.coordsAtPos(sel.from - completionWord.length - 1)
		// The box in which the tooltip is positioned, to use as base

		let innerDOMValue = view.dom.innerHTML
		dispatch('content', innerDOMValue)

		// Check types
		let marks = view.state.storedMarks || view.state.selection.$from.marks()

		let isBold = schema.marks.strong.isInSet(marks) != null
		let isItalic = schema.marks.em.isInSet(marks) != null
		let isStrike = schema.marks.strike.isInSet(marks) != null
		let isUnderline = schema.marks.underline.isInSet(marks) != null
		isEmpty = checkEmpty(innerDOMValue)
		let evt = {
			isEmpty: isEmpty,
			bold: isBold,
			isBoldEnabled: Commands.toggleStrong(view.state),
			italic: isItalic,
			isItalicEnabled: Commands.toggleItalic(view.state),
			strike: isStrike,
			isStrikeEnabled: Commands.toggleStrike(view.state),
			underline: isUnderline,
			isUnderlineEnabled: Commands.toggleUnderline(view.state),
			cursor: {
				left: cursor.left,
				top: cursor.top,
				bottom: cursor.bottom,
				right: cursor.right,
			},
			completionWord,
			completionEnd,
			selection: { from: sel.from, to: sel.to },
		} as EditorContentEvent
		dispatch('styleEvent', evt)
	}

	//****************************************************************
	// Initialization of prosemirror stuff.
	//****************************************************************
	rootElement = document.createElement('div')

	const parser = new window.DOMParser()
	const element = parser.parseFromString(content, 'text/html').body

	state = EditorState.create({
		schema,
		doc: DOMParser.fromSchema(schema).parse(element),
		plugins: [history(), buildInputRules(), keymap(buildKeymap())],
	})
	view = new EditorView(rootElement, {
		state,
		dispatchTransaction(transaction) {
			let newState = view.state.apply(transaction)

			// Check and update triggers to update content.
			if (transformInjections != null) {
				let tr: Promise<Transaction | null> = transformInjections(newState)
				if (tr != null) {
					tr.then((res) => {
						if (res != null) {
							newState = newState.apply(res)
							view.updateState(newState)

							emitStyleEvent()
						}
					})
				}
			}
			view.updateState(newState)

			emitStyleEvent()
		},
	})

	onMount(() => {
		root.appendChild(rootElement)
	})

	function updateValue() {
		if (content != view.dom.innerHTML) {
			const element = parser.parseFromString(content, 'text/html').body
			let newDoc = DOMParser.fromSchema(schema).parse(element)

			let op = state.tr
				.setSelection(new AllSelection(state.doc))
				.replaceSelectionWith(newDoc)
			let newState = state.apply(op)

			view.updateState(newState)

			view.focus()
		}
	}

	export function insert(text: string, from: number, to: number) {
		const t = view.state.tr.insertText(text, from, to)
		const st = view.state.apply(t)
		view.updateState(st)
		emitStyleEvent()
	}

	export function insertMark(
		text: string,
		from: number,
		to: number,
		mark: MarkType,
		attrs?: { [key: string]: any }
	) {
		// Ignore white spaces on end of text
		let markLen = text.trim().length

		const t = view.state.tr
			.insertText(text, from, to)
			.addMark(from, from + markLen, mark.create(attrs))
		const st = view.state.apply(t)
		view.updateState(st)
		emitStyleEvent()
	}
	// Some operations
	export function toggleBold() {
		Commands.toggleStrong(view.state, view.dispatch)
		view.focus()
	}
	export function toggleItalic() {
		Commands.toggleItalic(view.state, view.dispatch)
		view.focus()
	}
	export function toggleStrike() {
		Commands.toggleStrike(view.state, view.dispatch)
		view.focus()
	}
	export function toggleUnderline() {
		Commands.toggleUnderline(view.state, view.dispatch)
		view.focus()
	}
	export function toggleUnOrderedList() {
		Commands.toggleUnOrdered(view.state, view.dispatch)
		view.focus()
	}
	export function toggleOrderedList() {
		Commands.toggleOrdered(view.state, view.dispatch)
		view.focus()
	}
	export function focus() {
		view.focus()
	}
</script>

{#if isEmpty}
	<div class="hover-message">{hoverMessage}</div>
{/if}
<div class="edit-box" bind:this="{root}"></div>

<style lang="scss">
	:global {
		.ProseMirror {
			position: relative;
		}

		.ProseMirror {
			word-wrap: break-word;
			white-space: pre-wrap;
			white-space: break-spaces;
			-webkit-font-variant-ligatures: none;
			font-variant-ligatures: none;
			font-feature-settings: 'liga' 0; /* the above doesn't seem to work in Edge */
		}

		.ProseMirror pre {
			white-space: pre-wrap;
		}

		.ProseMirror li {
			position: relative;
		}

		.ProseMirror-hideselection *::selection {
			background: transparent;
		}
		.ProseMirror-hideselection *::-moz-selection {
			background: transparent;
		}
		.ProseMirror-hideselection {
			caret-color: transparent;
		}

		.ProseMirror-selectednode {
			outline: 2px solid #8cf;
		}

		/* Make sure li selections wrap around markers */

		li.ProseMirror-selectednode {
			outline: none;
		}

		li.ProseMirror-selectednode:after {
			content: '';
			position: absolute;
			left: -32px;
			right: -2px;
			top: -2px;
			bottom: -2px;
			border: 2px solid #8cf;
			pointer-events: none;
		}
	}

	.edit-box {
		overflow: scroll;
		height: 100%;
		width: 100%;

		:global {
			div {
				outline: none;
				p {
					margin: 5px;
				}
				// blockquote {
				//   border-left: 1.5px solid #bbb;
				//   margin: 5px;
				// }
			}
		}
	}
	.edit-box:focus {
		outline: none;
	}
	.hover-message {
		position: absolute;
		pointer-events: none;
		margin: 5px;
		color: #aaaaaa;
	}
</style>
