// v0.4/platform/ui/src/components/Label.svelte
<!--
// Copyright © 2020, 2021 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
  import type { IntlString } from '@anticrm/platform'
  import { translate } from '@anticrm/platform'

  export let label: IntlString
  export let params: Record<string, any> | undefined

  $: translation = translate(label, params ?? {})
</script>

{#await translation}
  {label}
{:then text}
  {text}
{/await}

// .v1/plugins/platform-vue/src/components/Label.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">

import { defineComponent, ref } from 'vue'
import { Platform, Metadata } from '@anticrm/platform'
import ui, { getPlatform } from '..'

export default defineComponent({
  props: {
    text: {
      type: [String, Promise]
    }
  },
  setup (props) {
    const text = props.text
    let content
    if (text instanceof Promise) {
      content = ref('')
      text.then(text => content.value = text)
    } else {
      content = text
    }

    return { content }
  }
})
</script>

<template>
  <span>{{content}}</span>
</template>
