// plugins/task/src/components/internal/CreateForm.svelte
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->
<script lang="ts">
  import { Ref, Class, Doc } from '@anticrm/core'
  import { createEventDispatcher, onMount } from 'svelte'
  import { AnyComponent } from '@anticrm/platform-ui'
  import presentation, { getComponentExtension } from '@anticrm/presentation'
  import { AttrModel, ClassModel } from '@anticrm/presentation'

  import AttributeEditor from '@anticrm/presentation/src/components/AttributeEditor.svelte'
  import Properties from '@anticrm/presentation/src/components/internal/Properties.svelte'
  import Icon from '@anticrm/platform-ui/src/components/Icon.svelte'
  import UserBox from '@anticrm/platform-ui/src/components/UserBox.svelte'
  import workbench from '@anticrm/workbench'
  import ReferenceInput from '@anticrm/presentation/src/components/refinput/ReferenceInput.svelte'
  import InlineEdit from '@anticrm/sparkling-controls/src/InlineEdit.svelte'
  import Button from '@anticrm/sparkling-controls/src/Button.svelte'
  import { CORE_CLASS_VDOC, Space } from '@anticrm/domains'
  import { getCoreService, getPresentationService } from '../../utils'

  export let title: string
  export let _class: Ref<Class<Doc>>
  export let space: Ref<Space>
  let object = {} as any

  let createFormComponent: AnyComponent
  const coreService = getCoreService()
  const dispatch = createEventDispatcher()

  let model: ClassModel | undefined
  let primary: AttrModel | undefined

  const presentationService = getPresentationService()

  function save () {
    const doc = {
      _class,
      [primary?.key || 'name']: title,
      _space: space, ...object
    }
    object = {}
    // absent VDoc fields will be autofilled
    coreService.create(_class, doc)
    dispatch('close')
  }

  const init = Promise.all([
    presentationService.then(ps => ps.getClassModel(_class, CORE_CLASS_VDOC)).then((m) => {
      const mp = m.filterPrimary()
      model = mp.model
      primary = mp.primary
    })
  ])

  let users: Array<{}> = [{
    id: 0,
    url: 'https://platform.exhale24.ru/images/photo-1.png',
    name: 'Александр Алексеенко'
  },
    {
      id: 1,
      url: 'https://platform.exhale24.ru/images/photo-2.png',
      name: 'Андрей Платов'
    },
    {
      id: 2,
      url: 'https://platform.exhale24.ru/images/photo-3.png',
      name: 'Сергей Буевич'
    },
    {
      id: 3,
      url: 'https://platform.exhale24.ru/images/photo-4.png',
      name: 'Андрей Соболев'
    }]
</script>

<style lang="scss">
  .recruiting-view {
    padding: 24px 32px 32px 32px;
    display: flex;
    flex-direction: column;
  }

  .header {
    display: flex;
    margin-bottom: 9px;

    .caption {
      flex-grow: 1;

      .caption-edit {
        width: 100%;
      }
    }

    .actions {
      display: flex;
      flex-grow: 1;
      flex-direction: row-reverse;
      font-size: 10px;

      button {
        margin-left: 0.5em;
      }
    }
  }

  .content {
    .taskLabel {
      color: var(--theme-doclink-color);
      margin-bottom: 16px;
    }

    .separator {
      height: 16px;
    }
  }

  .buttons {
    margin-top: 16px;
    display: grid;
    grid-template-columns: 1fr 1fr;
    column-gap: 16px;
  }

  .attributes {
    display: flex;
    flex-wrap: wrap;

    //display: grid;
    //background-color: $content-color-dark;
    //grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    //grid-gap: 1px;

    margin-top: 1em;

    .group {
      padding: 0.5em;
      //background-color: $content-bg-color;
    }
  }
</style>

<div class="recruiting-view">
  <div class="header">
    <div class="caption-1 caption">
      <InlineEdit bind:value={title} placeholder="Name" fullWidth="true" />
    </div>
    <a href="/" style="margin-left:1.5em" on:click|preventDefault={() => dispatch('close')}>
      <Icon icon={workbench.icon.Close} button="true" />
    </a>
  </div>

  <div class="content">
    <div class="taskLabel">
      DT-925
    </div>
    <UserBox items={users} />
    <div class="separator"></div>
    <ReferenceInput stylesEnabled="true" />
  </div>

  <div class="buttons">
    <Button kind="primary" on:click={save}>Принять</Button>
    <Button on:click={() => dispatch('close')}>Отказаться</Button>
  </div>
</div>

// packages/workbench/src/components/CreateForm.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">

import { defineComponent, PropType, reactive } from 'vue'
import { Class, CreateTx, Doc, generateId, Property, Ref, VDoc } from '@anticrm/platform'

import core from '@anticrm/platform-core'

import { getCoreService } from '@anticrm/workbench/src/utils'

import OwnAttributes from '@anticrm/presentation-ui/src/components/OwnAttributes.vue'
import InlineEdit from '@anticrm/sparkling-controls/src/InlineEdit.vue'
import Button from '@anticrm/sparkling-controls/src/Button.vue'

export default defineComponent({
  components: { InlineEdit, OwnAttributes, Button },
  props: {
    _class: {
      type: String as unknown as PropType<Ref<Class<VDoc>>>,
      required: true
    },
    title: {
      type: String,
      required: true
    },
    component: {
      type: String,
      required: true
    }
  },
  setup (props, context) {
    const coreService = getCoreService()

    const object = reactive({})

    function save () {
      coreService.createVDoc(props._class, object)
      context.emit('done', 'save')
    }

    function cancel () {
      context.emit('done', 'cancel')
    }

    return {
      object,
      save,
      cancel,
    }
  }
})
</script>

<template>
  <div class="recruiting-view">
    <div class="header">
      <div class="caption-4">{{title}}</div>
      <div class="actions">
        <Button @click="cancel">Cancel</Button>
        <Button @click="save">Save</Button>
      </div>
    </div>

    <div class="content">
      <widget :component="component" :object="object" :_class="_class" />
    </div>
  </div>
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

.recruiting-view {
  margin: 1em;

  .header {
    display: flex;

    .actions {
      display: flex;
      flex-grow: 1;
      flex-direction: row-reverse;
      font-size: 10px;

      button {
        margin-left: 0.5em;
      }
    }
  }

  .content {
    margin: 1em;
  }

  .attributes {
    display: flex;
    flex-wrap: wrap;

    //display: grid;
    //background-color: $content-color-dark;
    //grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    //grid-gap: 1px;

    margin-top: 1em;

    .group {
      padding: 0.5em;
      //background-color: $content-bg-color;
    }
  }
}
</style>
