// v0.4/plugins/login-impl/components/LoginForm.svelte
<!--
// Copyright © 2020, 2021 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->
<script lang="ts">
  import type { Platform } from '@anticrm/platform'
  import { Severity, Status } from '@anticrm/platform'
  import { getContext, onDestroy } from 'svelte'
  import type { LoginService } from '..'
  import login from '..'
  import Form from './Form.svelte'
  import Button from '@anticrm/sparkling-controls/src/Button.svelte'
  import type { ApplicationRoute, ApplicationRouter } from '@anticrm/platform-ui'
  import { PlatformStatusCodes } from '@anticrm/foundation'

  export let router: ApplicationRouter<ApplicationRoute>
  const object = { username: '', password: '', workspace: '', secondFactorCode: '' }
  let status: Status

  let loginActive = false
  let needSecondFactor = false
  const baseFields = [
    { name: 'username', i18n: 'Username' },
    {
      name: 'password',
      i18n: 'Password',
      password: true
    },
    { name: 'workspace', i18n: 'Workspace' }
  ]

  let fields
  $: fields = needSecondFactor ? baseFields.concat({ name: 'secondFactorCode', i18n: 'Confirm code' }) : baseFields

  const platform = getContext('platform') as Platform
  const loginService = platform.getPlugin(login.id)

  async function doLogin () {
    status = new Status(Severity.INFO, 0, 'Соединяюсь с сервером...')

    status = await (await loginService).doLogin(
      object.username,
      object.password,
      object.workspace,
      object.secondFactorCode
    )

    if (status.code === PlatformStatusCodes.CLIENT_VALIDATE_REQUIRED) {
      needSecondFactor = true
    }
  }

  // eslint-disable-next-line @typescript-eslint/no-empty-function
  async function doSignup () {}

  async function checkLoginInfo (ls: LoginService) {
    const info = await ls.getLoginInfo()
    if (info) {
      loginActive = true
      object.username = info.email
      object.workspace = info.workspace
    }
  }

  let timer: number
  // Auto forward to default application
  const loginCheck = loginService.then(async (ls) => {
    await checkLoginInfo(ls)

    timer = setInterval(async () => {
      await checkLoginInfo(ls)
    }, 1000)
  })

  onDestroy(() => {
    if (timer) {
      clearInterval(timer)
    }
  })

  async function navigateApp (): Promise<void> {
    (await loginService).navigateApp()
  }

  async function logout (): Promise<void> {
    (await loginService).doLogout()
    loginActive = false
  }

  function navigateSetting (): void {
    router.navigate({ route: 'setting' })
  }
</script>

{#await loginCheck then value}
  {#if loginActive}
    <div class="login-form-info">
      <div class="field">
        Logged in as: {object.username}
      </div>
      <div class="field">
        Workspace: {object.workspace}
      </div>
      <div class="actions">
        <Button width="100px" on:click={logout}>Logout</Button>
        <Button width="100px" on:click={navigateSetting}>Settings</Button>
        <Button width="100px" on:click={navigateApp}>Switch to Application</Button>
      </div>
    </div>
  {:else}
    <Form
      actions={[
        { i18n: 'Create Space', func: doSignup },
        { i18n: 'Login', func: doLogin }
      ]}
      {fields}
      {object}
      caption="Login into system"
      {status} />
  {/if}
{/await}

<style lang="scss">
  .login-form-info {
    margin: 20vh auto auto;
    width: 30em;
    padding: 2em;
    border-radius: 1em;
    border: 1px solid var(--theme-bg-accent-color);
    .actions {
      display: flex;
      margin-top: 1.5em;
    }
  }
</style>

// plugins/platform-login/src/internal/LoginForm.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
import { defineComponent, ref } from 'vue'

import EditBox from '@anticrm/sparkling-controls/src/EditBox.vue'
import Button from '@anticrm/sparkling-controls/src/Button.vue'

import login from '..'

import { encode } from 'jwt-simple'

type LoginInfo = { token?: string, wsUrl?: string, errorCode?: number }

export default defineComponent({
  components: {
    EditBox,
    Button,
  },
  setup () {
    const username = ref()
    const password = ref()

    const working = ref(false)

    function doLogin () {
      working.value = true
      console.log('login ', username.value, " ", password.value)
      const request = {
        username: username.value,
        password: password.value,
      }

      const url = login.metadata.LoginUrl
      const token = ''

      // fetch(url, {
      //   method: 'POST',
      //   headers: {
      //     'Content-Type': 'application/json;charset=utf-8'
      //   },
      //   body: JSON.stringify(request)
      // }).then(async (response) => {
      //   const json = await response.json() as LoginInfo
      //   if (json.errorCode) {
      //     console.log(json.errorCode)
      //   } else {
      //     this.$platform.setMetadata()
      //   }
      // })


    }

    return { doLogin, username, password, working }
  }
})
</script>

<template>
  <div id="login-form">
    <form>
      <div class="caption-2">Вход в систему</div>

      <slot name="working" v-if="working">Соединяюсь с сервером...</slot>
      <slot name="success" v-else-if="result">{{result}}</slot>
      <slot name="failure" v-else-if="error">{{error}}</slot>

      <div class="field">
        <EditBox placeholder="Электропочта" v-model="username" />
      </div>
      <div class="field">
        <EditBox type="password" placeholder="Пароль" v-model="password" />
      </div>

      <div class="actions">
        <Button>Зарегистрироваться</Button>
        <div class="separator" />
        <Button @click="doLogin">Войти в систему</Button>
      </div>
    </form>
  </div>
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

#login-form {
  form {
    margin: auto;
    margin-top: 100px;
    width: 30em;
    padding: 2em;
    border: 1px solid $workspace-separator-color;
    border-radius: 1em;

    .field {
      .crm-editbox {
        width: 100%;
      }
      margin: 1em 0;
    }

    .actions {
      display: flex;
      margin-top: 1.5em;

      .separator {
        width: 1em;
      }

      .crm-button {
        flex: 1;
      }
    }
  }
}
</style>
