// v0.4/plugins/ui-impl/src/components/internal/Root.svelte
<script lang="ts">
  import type { Metadata, Platform, Status } from '@anticrm/platform'
  import { PlatformStatus, Severity } from '@anticrm/platform'
  import type { ApplicationRoute, UIService } from '../..'
  import { CONTEXT_PLATFORM, CONTEXT_PLATFORM_UI, routeMeta } from '../..'
  import { setContext } from 'svelte'

  import Theme from '@anticrm/sparkling-theme/src/components/Theme.svelte'
  import StatusComponent from './Status.svelte'
  import Clock from './Clock.svelte'
  import ThemeSelector from './ThemeSelector.svelte'
  import Component from '../Component.svelte'
  import Modal from './Modal.svelte'
  import uiPlugin from '../../.'
  import { PlatformStatusCodes } from '@anticrm/foundation'
  import { newRouter } from '../../'

  export let platform: Platform
  export let ui: UIService

  setContext(CONTEXT_PLATFORM, platform)
  setContext(CONTEXT_PLATFORM_UI, ui)

  const defaultApp = platform.getMetadata(uiPlugin.metadata.DefaultApplication) || ''
  const authMeta = platform.getMetadata(uiPlugin.metadata.LoginApplication) || ''
  const authApp = platform.getMetadata(routeMeta(authMeta))

  let authenticationRequired = false

  let currentApp: ApplicationRoute | undefined
  let currentAppErr: string | undefined

  interface ApplicationInfo {
    application: string
  }

  newRouter<ApplicationInfo>(
    ':application',
    (route) => {
      let appRoute: Metadata<ApplicationRoute> = routeMeta(defaultApp)
      if (route.application && route.application.length > 0 && route.application !== '#default') {
        appRoute = routeMeta(route.application)
      }
      if (appRoute) {
        const routeAppComponent = platform.getMetadata(appRoute)
        if (routeAppComponent) {
          currentAppErr = undefined
          currentApp = routeAppComponent
          return
        }
      }
      if (!currentApp) {
        currentAppErr = `There is no application route defined for ${appRoute}`
      }
    },
    { application: '#default' }
  )

  const status: Status = { severity: Severity.OK, code: 0, message: '' }

  platform.addEventListener(PlatformStatus, (_event, status) => {
    if (status.severity === Severity.ERROR && status.code === PlatformStatusCodes.AUTHENTICATON_REQUIRED) {
      authenticationRequired = true
    } else if (status.severity === Severity.OK && status.code === PlatformStatusCodes.AUTHENTICATON_OK) {
      authenticationRequired = false
    }

    return Promise.resolve()
  })
</script>

<Theme>
  <div id="ui-root">
    <div class="status-bar">
      <div class="container">
        <div class="logo">&#x24C5;</div>
        <div class="status-messages">
          <StatusComponent {status} />
        </div>
        <div class="widgets">
          <div class="widget">
            <Clock />
          </div>
          <div class="widget">
            <ThemeSelector />
          </div>
          <!-- <div v-for="widget in widgets" :key="widget" class="widget">
            <widget :component="widget" />
          </div> -->
        </div>
      </div>
    </div>
    <div class="app">
      {#if authenticationRequired}
        <Component is={authApp.component} props={{}} />
      {:else if currentApp}
        <Component is={currentApp.component} props={{}} />
      {:else}
        <div class="caption-1 error">
          Could not find application: "{currentAppErr}"
        </div>
      {/if}
    </div>
  </div>
  <Modal />
</Theme>

<style lang="scss">
  @import '~@anticrm/sparkling-theme/styles/_global.scss';

  $status-bar-height: 20px;
  $pictogram-size: 51px;

  #ui-root {
    display: flex;
    flex-direction: column;

    height: 100vh;

    .status-bar {
      height: $status-bar-height;
      line-height: $status-bar-height;

      .container {
        display: flex;

        .logo {
          width: $pictogram-size;
          text-align: center;
          font-size: 1.25em;
          font-weight: 700;
        }

        .status-messages {
          flex-grow: 1;
          text-align: center;
        }

        .widgets {
          display: flex;
          flex-direction: row-reverse;

          .widget {
            padding-right: 1em;
            padding-left: 1em;
            font-weight: 700;
          }
        }
      }
    }

    .error {
      margin-top: 45vh;
      text-align: center;
    }

    .app {
      height: calc(100vh - #{$status-bar-height});
    }
  }
  :global(.theme-dark) .status-bar {
    border-bottom: 1px solid $theme-dark-bg-color;
  }
  :global(.theme-grey) .status-bar {
    border-bottom: 1px solid $theme-grey-bg-color;
  }
  :global(.theme-light) .status-bar {
    border-bottom: 1px solid $theme-light-bg-color;
  }
</style>

// packages/platform-ui/src/components/Root.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
// 
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// 
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
import { computed, defineComponent, ref } from 'vue'
import ui, { getPlatform, getUIService } from '..'
import { PlatformStatus, Severity, Status } from '@anticrm/platform'

import StatusComponent from './Status.vue'
import Clock from './widgets/Clock.vue'

export default defineComponent({
  components: { Status: StatusComponent, Clock },
  setup () {
    const platform = getPlatform()
    const uiService = getUIService()

    const status = ref(new Status(Severity.OK, 0, ''))
    const icon = ref('')

    platform.addEventListener(PlatformStatus, async (event: string, platformStatus: Status) => {
      status.value = platformStatus
    })

    const location = computed(() => uiService.getLocation())

    return { status, icon, location, spinner: ui.component.Spinner, widgets: uiService.widgets }
  }
})
</script>

<template>
  <div id="ui-root">
    <div class="status-bar">
      <div class="container">
        <div class="logo">&#x24C5;</div>
        <div class="status-messages">
          <Status :status="status" />
        </div>
        <div class="widgets">
          <div class="clock">
            <Clock />
          </div>
          <div v-for="widget in widgets" :key="widget" class="widget">
            <widget :component="widget" />
          </div>
        </div>
      </div>
    </div>
    <div class="app">
      <widget
        :component="location.app"
        :fallback="spinner"
        :location="location"
        v-if="location.app"
      />
      <!--        :path="current.path"-->
      <!--        :params="current.params"-->
      <div v-else class="caption-1 error">No application provided.</div>
    </div>
  </div>
</template>

<style lang="scss">
@import "~@anticrm/sparkling-theme/css/_globals.scss";
@import "~@anticrm/sparkling-theme/css/_variables.scss";

$status-bar-height: 20px;

#ui-root {
  @include root-style;

  display: flex;
  flex-direction: column;

  height: 100vh;

  .status-bar {
    background-color: $side-bg-color;
    color: $content-color;
    height: $status-bar-height;
    line-height: $status-bar-height;
    border-bottom: 1px solid $nav-bg-color;
    /*box-sizing: border-box;*/

    .container {
      display: flex;

      .logo {
        width: $pictogram-size;
        text-align: center;
        /*padding-left: 1em;*/
        /*padding-right: 1em;*/

        font-size: 1.25em;
        font-weight: 700;

        border-right: 1px solid $nav-bg-color;
      }

      .status-messages {
        flex-grow: 1;
        text-align: center;
      }

      .widgets {
        display: flex;
        flex-direction: row-reverse;

        .widget {
          border-left: 1px solid $nav-bg-color;
          padding-right: 1em;
          padding-left: 1em;
          font-weight: 700;
        }

        .clock {
          border-left: 1px solid $nav-bg-color;
          padding-right: 1em;
          padding-left: 1em;
          font-weight: 700;
        }
      }
    }
  }

  .error {
    margin-top: 45vh;
    text-align: center;
  }

  .app {
    height: calc(100vh - #{$status-bar-height});
    background-color: $content-bg-color;
  }
}
</style>
