// packages/platform-vue/src/components/calendars/MonthCalendar.vue
<!--
// Copyright © 2020 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->

<script lang="ts">
import { defineComponent, PropType, inject } from 'vue';
import core, { Obj, Doc, Ref, Class, CoreService } from '@anticrm/platform-core';
import ui, { UIService } from '@anticrm/platform-ui';

import CalendarDay from "./CalendarDay.vue";

export default defineComponent({
  components: { CalendarDay },
  props: {
    /**
     * If passed calendar will use Monday as first day.
     */
    mondayStart: {
      type: Boolean,
      default: true,
    },
    weekFormat: {
      type: String,
      default: "short",
    },
    /**
     * Date to show calendar month on.
     */
    date: {
      type: Date,
      default: () => new Date()
    },
  },
  setup(props) {
    console.log("setup", props.date)
    return {
      // date: props.date || new Date(),
      weekFormat: props.weekFormat || 'short',
      mondayStart: props.mondayStart || true,
      /**
       * Return a month calendar first day
       * @param mondayStart
       * @param date
       */
      firstDay(): Date {
        let firstDayOfMonth = new Date(this.date)
        firstDayOfMonth.setDate(1) // First day of month
        let result = new Date(firstDayOfMonth)
        result.setDate(
          result.getDate() - result.getDay() + (this.mondayStart ? 1 : 0)
        )

        // Check if we Need add one more week
        if (result.getTime() > firstDayOfMonth.getTime()) {
          result.setDate(result.getDate() - 7)
        }
        return result
      },
      /**
       * Return a weekday name
       */
      getWeekDayName(weekDay: Date): string {
        let locale = new Intl.NumberFormat().resolvedOptions().locale;
        return new Intl.DateTimeFormat(locale, {
          weekday: this.weekFormat
        }).format(weekDay)
      },
      /**
       * Return firstDay with offset to passed offset
       */
      day(offset: number): Date {
        return new Date(this.firstDay().getTime() + offset * 86400000)
      }
    };
  }
});
</script>

<template>
  <div class="erp-calendar">
    <div class="thead">
      <div class="th" v-for="d in 7" :key="'w_'+d">{{getWeekDayName(day(d-1))}}</div>
    </div>
    <div class="tbody">
      <div class="tr" v-for="w in 6" :key="'week_'+w">
        <CalendarDay v-for="d in 7" :key="'d_'+d" v-bind:date="day((w-1)*7 + (d-1))" />
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import "~@anticrm/sparkling-theme/css/_variables.scss";

.erp-calendar {
  display: table;
  border-collapse: collapse;
  background-color: $content-bg-color;

  .tr {
    display: table-row;
  }

  .thead {
    display: table-header-group;
  }

  .th {
    display: table-cell;
    // padding: 0.5em;
    text-align: center;
  }

  .tbody {
    display: table-row-group;

    .tr {
      border-bottom: $border-default;
    }
  }
}
</style>

// packages/sparkling-controls/src/calendar/MonthCalendar.svelte
<!--
// Copyright © 2021 Anticrm Platform Contributors.
//
// Licensed under the Eclipse Public License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. You may
// obtain a copy of the License at https://www.eclipse.org/legal/epl-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
-->
<script type="ts">
  import Button from '@anticrm/sparkling-controls/src/Button.svelte'
  import {
    areDatesEqual,
    day,
    firstDay,
    getMonthName,
    getWeekDayName,
    incrementMonth,
    isWeekend,
    weekday
  } from './internal/DateUtils'

  export let mondayStart: boolean = false
  export let weekFormat: 'narrow' | 'short' | 'long' | undefined = 'short'
  export let selectedDate: Date | undefined = undefined
  export let todayDate: Date = new Date()

  let currentDate: Date = selectedDate || todayDate
  let firstDayOfCurrentMonth: Date = firstDay(currentDate, mondayStart)

  function onSelect(date: Date) {
    selectedDate = date
  }

  function incMonth(count: number) {
    if (count) {
      currentDate = incrementMonth(currentDate, count)
      firstDayOfCurrentMonth = firstDay(currentDate, mondayStart)
    }
  }
</script>

<div class="month-calendar">
  <div class="selected-month-controller">
    <Button size="small" on:click={() => incMonth(-1)}>&lt;</Button>
    <div class="month-name">{getMonthName(currentDate) + ' ' + currentDate.getFullYear()}</div>
    <Button size="small" on:click={() => incMonth(1)}>&gt;</Button>
  </div>
  <div class="days-of-week-header">
    {#each [...Array(7).keys()] as dayOfWeek}
      <div class="day-name">{getWeekDayName(day(firstDayOfCurrentMonth, dayOfWeek), weekFormat)}</div>
    {/each}
  </div>
  <div class="days-of-month">
    {#each [...Array(6).keys()] as weekIndex}
      {#each [...Array(7).keys()] as dayOfWeek}
        <div
          class="cell"
          class:weekend={isWeekend(weekday(firstDayOfCurrentMonth, weekIndex, dayOfWeek))}
          class:today={areDatesEqual(todayDate, weekday(firstDayOfCurrentMonth, weekIndex, dayOfWeek))}
          class:selected={areDatesEqual(selectedDate, weekday(firstDayOfCurrentMonth, weekIndex, dayOfWeek))}
          on:click={() => onSelect(weekday(firstDayOfCurrentMonth, weekIndex, dayOfWeek))}
        >
          {weekday(firstDayOfCurrentMonth, weekIndex, dayOfWeek).getDate()}
        </div>
      {/each}
    {/each}
  </div>
</div>

<style lang="scss">
  .day-name,
  .selected-month-controller {
    display: flex;
    justify-content: center;
  }
  .days-of-week-header,
  .days-of-month {
    display: grid;
    grid-template-columns: repeat(7, 1fr);
  }
  .weekend {
    background-color: var(--theme-bg-accent-color);
  }
  .today {
    color: #a66600;
  }
  .selected {
    border-radius: 3px;
    color: var(--theme-content-dark-color);
    background-color: var(--theme-bg-dark-color);
  }
  .cell {
    height: 100%;
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .cell:hover {
    border-radius: 3px;
    background-color: var(--theme-bg-dark-hover);
    color: var(--theme-content-color);
  }
  .month-name {
    color: var(--theme-content-dark-color);
    font-size: 14px;
    font-weight: bold;
    margin: 0 5px;
  }
</style>
